version: '1.0'

services:
  wechat:
    container_name: wechat
    build: .
    image: wechat-appimage
    ports:
      - "6080:6080"         # noVNC 网页访问端口
    shm_size: "2g"          # 必须，加大共享内存，避免卡顿
    restart: unless-stopped
    volumes:
      - ./data:/root        # 持久化微信配置文件（可选）
    environment:
      - DISPLAY=:0
      - DISPLAY_RESOLUTION=1440x900x24

    command: ["/opt/startup.sh"]   # ✅ 关键行：显式设定启动脚本
