version: '1.1'

services:
  wechat:
    container_name: wechat
    build: .
    image: wechat-appimage
    ports:
      - "6080:6080"
    shm_size: "2g"
    restart: unless-stopped
    volumes:
      - ./data:/root
    environment:
      - DISPLAY=:0
      - GTK_IM_MODULE=fcitx
      - QT_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - VNC_PASSWORD=wechat123

